### ISSUE TITLE
webpack error

### ISSUE THREAD

**Issue by KevinCarroll7737** [centrual/cordova-template-framework7-vue-webpack#118]
Every time I install a new npm package, when I do a relase, I get this error.

```bash
$ npm i html-webpack-plugin --save-dev
$ cordova build android --release
Before deploy hook started...
Checking is node modules installed...
Node modules already installed.
Starting webpack build...
Error happened when webpack build: Error: Command failed: "/home/srbz/cordova_building_1_3_0_0/node_modules/.bin/webpack" --env.release
[BABEL] Note: The code generator has deoptimised the styling of "/home/srbz/cordova_building_1_3_0_0/node_modules/framework7/dist/framework7.esm.bundle.js" as it exceeds the max of "500KB".

Webpack build completed to www folder successfully!
Error happened on main chain:
Error: Error happened when webpack build: Error: Command failed: "/home/srbz/cordova_building_1_3_0_0/node_modules/.bin/webpack" --env.release
[BABEL] Note: The code generator has deoptimised the styling of "/home/srbz/cordova_building_1_3_0_0/node_modules/framework7/dist/framework7.esm.bundle.js" as it exceeds the max of "500KB".

    at exec (/home/srbz/cordova_building_1_3_0_0/hooks/hookers.js:184:19)
    at ChildProcess.exithandler (child_process.js:280:5)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Socket.stream.socket.on (internal/child_process.js:353:11)
    at Socket.emit (events.js:180:13)
    at Pipe._handle.close [as _onclose] (net.js:541:12)
(node:15413) UnhandledPromiseRejectionWarning: Error: Error happened when webpack build: Error: Command failed: "/home/srbz/cordova_building_1_3_0_0/node_modules/.bin/webpack" --env.release
[BABEL] Note: The code generator has deoptimised the styling of "/home/srbz/cordova_building_1_3_0_0/node_modules/framework7/dist/framework7.esm.bundle.js" as it exceeds the max of "500KB".

    at exec (/home/srbz/cordova_building_1_3_0_0/hooks/hookers.js:184:19)
    at ChildProcess.exithandler (child_process.js:280:5)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Socket.stream.socket.on (internal/child_process.js:353:11)
    at Socket.emit (events.js:180:13)
    at Pipe._handle.close [as _onclose] (net.js:541:12)
(node:15413) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15413) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by caiobiodere** [comment]
Did you try updating your cordova and packages versions?

**Comment by caiobiodere** [comment]
Ok I think yes, just let me know anything else

**Comment by KevinCarroll7737** [comment]
Thanks for the quick answer and sorry man A LOT going on here.

```bash
$ cd cordova-template-framework7-vue-webpack
$ cordova build --release android
[...]
BUILD SUCCESSFUL in 7s

$ npm i waitjs --save-dev #or What ever else
+ waitjs@0.2.0
added 1 package from 1 contributor, removed 798 packages and updated 70 packages in 10.981s
$ cordova build --release android
Before deploy hook started...
Checking is node modules installed...
Node modules already installed.
Starting webpack build...
Error happened when webpack build: Error: Command failed: "/home/srbz/cordova_building/node_modules/.bin/webpack" --env.release
[BABEL] Note: The code generator has deoptimised the styling of "/home/srbz/cordova_building/node_modules/framework7/dist/framework7.esm.bundle.js" as it exceeds the max of "500KB".

Webpack build completed to www folder successfully!
Error happened on main chain:
Error: Error happened when webpack build: Error: Command failed: "/home/srbz/cordova_building/node_modules/.bin/webpack" --env.release
[BABEL] Note: The code generator has deoptimised the styling of "/home/srbz/cordova_building/node_modules/framework7/dist/framework7.esm.bundle.js" as it exceeds the max of "500KB".

    at exec (/home/srbz/cordova_building/hooks/hookers.js:184:19)
    at ChildProcess.exithandler (child_process.js:280:5)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
(node:3481) UnhandledPromiseRejectionWarning: Error: Error happened when webpack build: Error: Command failed: "/home/srbz/cordova_building/node_modules/.bin/webpack" --env.release
[BABEL] Note: The code generator has deoptimised the styling of "/home/srbz/cordova_building/node_modules/framework7/dist/framework7.esm.bundle.js" as it exceeds the max of "500KB".

    at exec (/home/srbz/cordova_building/hooks/hookers.js:184:19)
    at ChildProcess.exithandler (child_process.js:280:5)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
(node:3481) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3481) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

$ npm update
[...]
+ node-sass@4.9.3
+ cordova-android@7.1.1
+ vue-template-compiler@2.5.17
+ uglifyjs-webpack-plugin@1.3.0
+ vue@2.5.17
+ cordova-browser@5.0.4
+ uglify-js@3.4.7
+ babel-loader@7.1.5
added 9 packages from 10 contributors, removed 31 packages and updated 60 packages in 10.998s

$ cordova build --release android
Before deploy hook started...
Checking is node modules installed...
Node modules already installed.
Starting webpack build...
Error happened when webpack build: Error: Command failed: "/home/srbz/cordova_building/node_modules/.bin/webpack" --env.release
[BABEL] Note: The code generator has deoptimised the styling of "/home/srbz/cordova_building/node_modules/framework7/dist/framework7.esm.bundle.js" as it exceeds the max of "500KB".

Webpack build completed to www folder successfully!
Error happened on main chain:
Error: Error happened when webpack build: Error: Command failed: "/home/srbz/cordova_building/node_modules/.bin/webpack" --env.release
[BABEL] Note: The code generator has deoptimised the styling of "/home/srbz/cordova_building/node_modules/framework7/dist/framework7.esm.bundle.js" as it exceeds the max of "500KB".

    at exec (/home/srbz/cordova_building/hooks/hookers.js:184:19)
    at ChildProcess.exithandler (child_process.js:280:5)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
(node:3550) UnhandledPromiseRejectionWarning: Error: Error happened when webpack build: Error: Command failed: "/home/srbz/cordova_building/node_modules/.bin/webpack" --env.release
[BABEL] Note: The code generator has deoptimised the styling of "/home/srbz/cordova_building/node_modules/framework7/dist/framework7.esm.bundle.js" as it exceeds the max of "500KB".

    at exec (/home/srbz/cordova_building/hooks/hookers.js:184:19)
    at ChildProcess.exithandler (child_process.js:280:5)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
(node:3550) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3550) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

$ ls platforms
android
browser
```

Any idea?

**Comment by KevinCarroll7737** [comment]
Sorry my man. I was all wrong.. Thanks for the support :)
