### ISSUE TITLE
Feature Request: Improve Webpack Error Messages

### ISSUE THREAD

**Issue by katk0smos** [centrual/cordova-template-framework7-vue-webpack#130]
The current error messages given out by webpack aren't very verbose and don't describe the problem.
For instance, it usually outputs something similar to this:
```bash
$ cordova run browser
Before deploy hook started...
Checking is node modules installed...
Node modules already installed.
Starting webpack build...
Error happened when webpack build: Error: Command failed: "./node_modules/.bin/webpack"

Webpack build completed to www folder successfully!
Error happened on main chain:
Error: Error happened when webpack build: Error: Command failed: "./node_modules/.bin/webpack"

    at exec (./hooks/hookers.js:184:19)
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
(node:9507) UnhandledPromiseRejectionWarning: Error: Error happened when webpack build: Error: Command failed: "./node_modules/.bin/webpack"

    at exec (./hooks/hookers.js:184:19)
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
(node:9507) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9507) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Improving the error messages would help to let us see exactly where and what the error is.

Of course, an alternative would be adding a linter, e.g. ESLint.

**Comment by caiobiodere** [comment]
I think that ESLint way is a good one for now 👍 I will work through your way

**Comment by caiobiodere** [comment]
@TheWaffleDimension I fixed that problem that was not showing webpack errors and probably going to put ESLint into the new version, thank you for your feedback

Last release: https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/releases/tag/2.0.10
