### ISSUE TITLE
error webpack build

### ISSUE THREAD

**Issue by jeryckho** [centrual/cordova-template-framework7-vue-webpack#132]
Hello there.

I've got this error when i launch `cordova run browser`:

```
Before deploy hook started...
Checking is node modules installed...
Node modules already installed.
Starting webpack build...
Error happened when webpack build: Error: Command failed: "C:\Prj\newmultisend\node_modules\.bin\webpack.cmd"

Webpack build completed to www folder successfully!
Error happened on main chain:
Error: Error happened when webpack build: Error: Command failed: "C:\Prj\newmultisend\node_modules\.bin\webpack.cmd"

    at exec (C:\Prj\newmultisend\hooks\hookers.js:184:19)
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
Error happened when webpack build: Error: Command failed: "C:\Prj\newmultisend\node_modules\.bin\webpack.cmd"
```
Win7 / node 8.11.4 / npm  4.1.2 / Cordova 8.1.2

**Comment by eXployd** [comment]
Same error in android for me cant build anything except for IOS platform.

**Comment by caiobiodere** [comment]
I checked you guys error, sorry by my mistake I forgot to put the material icons library into package.json.

Please use this release: https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/releases/tag/2.0.10
