### ISSUE TITLE
Error webpack build  android release

### ISSUE THREAD

**Issue by lastees** [centrual/cordova-template-framework7-vue-webpack#174]
Hello 
Command `cordova build android` is work . But I've got this error when i launch `cordova build android --release`  : 
```
ERROR in ./node_modules/framework7-icons/css/framework7-icons.css 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
> @font-face {
|   font-family: 'Framework7 Icons';
|   font-style: normal;
 @ ./src/main.js 23:23-75

ERROR in ./node_modules/material-design-icons/iconfont/material-icons.css 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
> @font-face {
|   font-family: 'Material Icons';
|   font-style: normal;
 @ ./src/main.js 27:21-81

ERROR in ./node_modules/framework7/css/framework7.bundle.min.css 13:0
Module parse failed: Unexpected token (13:0)
You may need an appropriate loader to handle this file type.
[...]
ERROR in ./node_modules/@fortawesome/fontawesome-free/css/all.min.css 5:0
Module parse failed: Unexpected token (5:0)
You may need an appropriate loader to handle this file type.
|  * License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
[...]
Error happened on main chain:
Error: Error happened when webpack build: Error: Command failed: "C:\Users\NL\projects\miroscopegroupp_front\node_modules\.bin\webpack.cmd" --env.release

    at exec (C:\Users\NL\projects\miroscopegroupp_front\hooks\hookers.js:184:19)
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
Error happened when webpack build: Error: Command failed: "C:\Users\NL\projects\miroscopegroupp_front\node_modules\.bin\webpack.cmd" --env.release
```
I use this versions: 
```
"framework7": "^4.4.0",
"framework7-icons": "^2.3.1",
 "framework7-vue": "^4.4.0",
 "material-design-icons": "^3.0.1",
 "vue": "^2.6.10",
 "vuex": "^3.1.1",
```
Thank you

**Comment by caiobiodere** [comment]
Hi @lastees hope you are having a good day, I just did some tests with your comments, and everything seems to work perfectly now, could you please try it again with the new [2.4.3 Version](https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/releases/tag/2.4.3)

**Comment by caiobiodere** [comment]
I am considering it as closed. Please let me know in case of any errors appears to you

**Comment by lastees** [comment]
@caiobiodere I'll let you know if something goes wrong.
Thanks for your template)
