### ISSUE TITLE
Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by imrealashu** [centrual/cordova-template-framework7-vue-webpack#184]
Webpack build completed to www folder successfully!
Error happened on main chain:
Error: Error happened when webpack build: Error: Command failed: "/Users/imrealashu/Playground/framework7-vue/node_modules/.bin/webpack"
(node:8813) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

    at /Users/imrealashu/Playground/framework7-vue/hooks/hookers.js:184:34
    at ChildProcess.exithandler (child_process.js:302:5)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12)
Error happened when webpack build: Error: Command failed: "/Users/imrealashu/Playground/framework7-vue/node_modules/.bin/webpack"
(node:8813) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

>npm list tapable
```├─┬ html-webpack-plugin@3.2.0
│ └── tapable@1.1.3
├─┬ webpack@4.43.0
│ ├─┬ enhanced-resolve@4.1.1
│ │ └── tapable@1.1.3  deduped
│ └── tapable@1.1.3  deduped
└─┬ webpack-cli@3.3.11
  └─┬ enhanced-resolve@4.1.0
    └── tapable@1.1.3  deduped```

Package JSON Dependencies

```"html-webpack-plugin": "^3.2.0",
"webpack": "^4.40.2",
"webpack-cli": "^3.3.9",
"webpack-dev-server": "^3.8.1",
"webpack-merge": "^4.2.2"```

**Comment by rtaparay** [comment]
any solution?, I have the same error 
I want to use it for a new project
![36](https://user-images.githubusercontent.com/50549119/173167990-4a8b95d1-864e-436c-8f29-719a8395e99d.png)
![37](https://user-images.githubusercontent.com/50549119/173168006-3f1c0078-0be8-403f-9196-e2a5c68afe81.png)


@caiobiodere  help please
