### ISSUE TITLE
Webpack Error on cordova build | cordova run

### ISSUE THREAD

**Issue by scorpionking2k5** [centrual/cordova-template-framework7-vue-webpack#55]
Just after creating a new project using:
`
cordova create <project_create_dir> [com.example.projectname] [ProjectClassName] --template cordova-template-framework7-vue-webpack
`
I did `cordova add platform browser `.
After that on running `cordova run browser`, I'm getting the following:

`Before deploy hook started...
Checking is node modules installed...
Node modules already installed.
Starting webpack build...
Error happened when webpack build: Error: Command failed: "/Users/myuser/Desktop/myproj/node_modules/.bin/webpack"

Webpack build completed to www folder successfully!
Error happened on main chain:
Error: Error happened when webpack build: Error: Command failed: "/Users/myuser/Desktop/myproj/node_modules/.bin/webpack"

    at exec (/Users/myuser/Desktop/myproj/hooks/hookers.js:187:19)
    at ChildProcess.exithandler (child_process.js:277:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
Error: Error happened when webpack build: Error: Command failed: "/Users/myuser/Desktop/myproj/node_modules/.bin/webpack"

`

**Comment by centrual** [comment]
Can you use `/Users/myuser/Desktop/myproj/node_modules/.bin/webpack` command directly in `/Users/myuser/Desktop/myproj/` folder?

**Comment by scorpionking2k5** [comment]
In main.js, I commented out
//import Framework7 from 'framework7'
but still getting this error.
vue and framework7 is undefined or not installed. I ran npm install too, but still the same error.


Hash: 0e8a5cb865c8b52ba7a3
Version: webpack 2.7.0
Time: 1231ms
                       Asset       Size  Chunks             Chunk Names
0e8a5cb865c8b52ba7a3.main.js     106 kB       0  [emitted]  main
                  index.html  434 bytes          [emitted]  
   [0] ./~/vue-loader/lib/component-normalizer.js 1.27 kB {0} [built]
   [1] ./src/main.vue 1.28 kB {0} [built]
   [2] ./src/assets/sass/main.scss 1.1 kB {0} [built]
   [3] ./src/routes.js 313 bytes {0} [built]
   [6] ./~/css-loader!./~/sass-loader/lib/loader.js!./src/assets/sass/main.scss 2.96 kB {0} [built]
  [10] ./src/assets/vue/pages/about.vue 1.33 kB {0} [built]
  [11] ./src/assets/vue/pages/dynamic-route.vue 1.37 kB {0} [built]
  [12] ./src/assets/vue/pages/form.vue 1.33 kB {0} [built]
  [13] ./~/vue-loader/lib/selector.js?type=script&index=0!./src/assets/vue/pages/about.vue 55 bytes {0} [built]
  [14] ./~/vue-loader/lib/selector.js?type=script&index=0!./src/assets/vue/pages/dynamic-route.vue 103 bytes {0} [built]
  [16] ./~/vue-loader/lib/selector.js?type=script&index=0!./src/main.vue 481 bytes {0} [built]
  [18] ./~/vue-loader/lib/template-compiler?{"id":"data-v-162c5bad"}!./~/vue-loader/lib/selector.js?type=template&index=0!./src/assets/vue/pages/form.vue 6.85 kB {0} [built]
  [20] ./~/vue-loader/lib/template-compiler?{"id":"data-v-65923500"}!./~/vue-loader/lib/selector.js?type=template&index=0!./src/main.vue 6.71 kB {0} [built]
  [21] ./~/vue-style-loader/lib/addStylesClient.js 6.05 kB {0} [built]
  [24] ./src/main.js 1.07 kB {0} [built]
    + 10 hidden modules

ERROR in ./src/main.js
Module not found: Error: Can't resolve 'framework7-vue' in '/Users/myuser/myproj/src'
 @ ./src/main.js 8:0-42

ERROR in ./src/main.js
Module not found: Error: Can't resolve 'vue' in '/Users/myuser/myproj/src'
 @ ./src/main.js 2:0-21

ERROR in ./src/main.js
Module not found: Error: Can't resolve 'framework7/dist/css/framework7.ios.min.css' in '/Users/myuser/myproj/src'
 @ ./src/main.js 11:0-72

ERROR in ./src/main.js
Module not found: Error: Can't resolve 'framework7/dist/css/framework7.ios.colors.min.css' in '/Users/myuser/myproj/src'
 @ ./src/main.js 12:0-85
Child html-webpack-plugin for "index.html":
       [0] ./~/lodash/lodash.js 540 kB {0} [built]
       [1] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 886 bytes {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]

**Comment by centrual** [comment]
Interesting, i think it's not search in node_modules directory.

What is your OS? (Mac, Linux)

**Comment by scorpionking2k5** [comment]
It's not. :(

There are vue-loader, vue-hot-reload, vue-template-compiler ... but no vue or fw7.
I'm on OSX 10.11.16

**Comment by scorpionking2k5** [comment]
fixed it.
npm install was probably using package-lock.json as a reference. It did not have vue and fw7 defined.
I removed it and ran npm install again. All required deps got installed and its building successfully now.

I'm not very familiar with the concept of package-lock.json . Not sure if it's being written incorrectly or was I missing a flag to choose the original package.json while running npm install.

Thanks for your time.

**Comment by centrual** [comment]
Oh, thanks for response :)
