### ISSUE TITLE
Error happened when webpack build, because of Uglifyjs. How to disable it?

### ISSUE THREAD

**Issue by Jaspur** [centrual/cordova-template-framework7-vue-webpack#73]
```
▶ phonegap emulate ios --target="iPad-Air"
[phonegap] executing 'cordova emulate ios --target=iPad-Air ' ...
Before deploy hook started...

Checking is node modules installed...

Node modules already installed.

Starting webpack build...

Error happened when webpack build: Error: Command failed: "/Users/MB/Code/Foobar/phonegap/node_modules/.bin/webpack"


Webpack build completed to www folder successfully!

Error happened on main chain:

Error: Error happened when webpack build: Error: Command failed: "/Users/MB/Code/Foobar/phonegap/node_modules/.bin/webpack"

    at exec (/Users/MB/Code/Foobar/phonegap/hooks/hookers.js:187:19)
    at ChildProcess.exithandler (child_process.js:205:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)

Error: Error happened when webpack build: Error: Command failed: "/Users/MB/Code/Foobar/phonegap/node_modules/.bin/webpack"
```

It's after adding some working Vue components.

**Comment by Jaspur** [comment]
```
▶ ./node_modules/.bin/webpack --env.release


Hash: 4e322b806eb2fca66ad4
Version: webpack 2.7.0
Time: 13291ms
                                        Asset       Size  Chunks                    Chunk Names
i-f7-ios.png?b356cb6518f2679e2645d1224914af9a    7.29 kB          [emitted]
                 4e322b806eb2fca66ad4.main.js     575 kB       0  [emitted]  [big]  main
                                   styles.css     310 kB       0  [emitted]  [big]  main
                                   index.html  472 bytes          [emitted]
  [10] ./~/vue-loader/lib/component-normalizer.js 1.27 kB {0} [built]
  [11] ./~/framework7/dist/css/framework7.ios.colors.min.css 41 bytes {0} [built]
  [12] ./~/framework7/dist/css/framework7.ios.min.css 41 bytes {0} [built]
  [13] ./~/framework7-vue/dist/framework7-vue.min.js 86.3 kB {0} [built]
  [14] ./~/framework7/dist/js/framework7.js 830 kB {0} [built]
  [15] ./src/main.vue 1.27 kB {0} [built]
  [16] ./src/assets/sass/main.scss 1.1 kB {0} [built]
  [17] ./~/vue/dist/vue.common.js 287 kB {0} [built]
  [18] ./src/routes.js 114 bytes {0} [built]
  [20] ../~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/main.vue 1.27 kB {0} [built]
  [45] ./~/timers-browserify/main.js 1.36 kB {0} [built]
  [47] ./~/vue-loader/lib/template-compiler?{"id":"data-v-0fbb1d26"}!./~/vue-loader/lib/selector.js?type=template&index=0!./src/main.vue 16 kB {0} [built]
  [51] ./src/main.js 1.07 kB {0} [built]
  [53] ./~/css-loader!./~/framework7/dist/css/framework7.ios.min.css 182 kB [built]
  [55] ./~/style-loader/addStyles.js 6.91 kB [built]
    + 41 hidden modules

ERROR in ./~/vue-loader/lib/template-compiler?{"id":"data-v-0fbb1d26"}!./~/vue-loader/lib/selector.js?type=template&index=0!./src/main.vue
Module not found: Error: Can't resolve '../src/images/examples/pikanto.jpg' in '/Users/MB/Code/Foobar/phonegap/src'
 @ ./~/vue-loader/lib/template-compiler?{"id":"data-v-0fbb1d26"}!./~/vue-loader/lib/selector.js?type=template&index=0!./src/main.vue 57:13-58 79:13-58
 @ ./src/main.vue
 @ ./src/main.js
Child html-webpack-plugin for "index.html":
       [0] ./~/lodash/lodash.js 540 kB {0} [built]
       [1] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 887 bytes {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.19 kB {0} [built]
       [1] ./~/framework7/dist/img/i-f7-ios.png 91 bytes {0} [built]
       [2] ./~/base64-js/index.js 3.47 kB {0} [built]
       [3] ./~/buffer/index.js 48.6 kB {0} [built]
       [4] ./~/css-loader!./~/framework7/dist/css/framework7.ios.min.css 182 kB {0} [built]
       [5] ./~/ieee754/index.js 2.05 kB {0} [built]
       [6] ./~/isarray/index.js 132 bytes {0} [built]
       [7] (webpack)/buildin/global.js 509 bytes {0} [built]
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.19 kB {0} [built]
       [1] ./~/base64-js/index.js 3.47 kB {0} [built]
       [2] ./~/buffer/index.js 48.6 kB {0} [built]
       [3] ./~/css-loader!./~/framework7/dist/css/framework7.ios.colors.min.css 129 kB {0} [built]
       [4] ./~/ieee754/index.js 2.05 kB {0} [built]
       [5] ./~/isarray/index.js 132 bytes {0} [built]
       [6] (webpack)/buildin/global.js 509 bytes {0} [built]
```

How to disable Uglifyjs?

**Comment by Jaspur** [comment]
@centrual when disabling ```vue-loader``` in webpack.config.js I get:
```
ERROR in ./src/main.vue
Module parse failed: /Users/MB/Code/Foobar/phonegap/src/main.vue Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <template>
|   <div id="app">
|
 @ ./src/main.js 25:0-28

ERROR in ./src/assets/vue/pages/settings.vue
Module parse failed: /Users/MB/Code/Foobar/phonegap/src/assets/vue/pages/settings.vue Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <template>
|   <f7-page id="settings-page" class="purple no-padding-top">
|
 @ ./src/routes.js 5:17-59
 @ ./src/main.js
```

**Comment by centrual** [comment]
You can disable the uglifyjs or you can install newest version of uglifyjs.

for disable uglifyjs just delete the https://github.com/centrual/cordova-template-framework7-vue-webpack/blob/master/template_src/webpack.config.js#L115

for update to latest version:
1) change https://github.com/centrual/cordova-template-framework7-vue-webpack/blob/master/template_src/package.json#L28 to `^1.1.1`
2) change https://github.com/centrual/cordova-template-framework7-vue-webpack/blob/master/template_src/package.json#L29 to `^3.2.0`
3) run `npm update`
4) uglifyjs will run.

Note: Some commands of phonegap not working well with this template.

Have a great day!

**Comment by Jaspur** [comment]
@centrual, check your outlook mailbox
