### ISSUE TITLE
bugged example! cordova run browser/ios -- --live-reload

### ISSUE THREAD

**Issue by renege** [centrual/cordova-template-framework7-vue-webpack#75]
Error:
```
$ cordova run browser -- --live-reload
Before deploy hook started...
Checking is node modules installed...
Node modules already installed.
Watcher ready!
Project is running at http://192.168.2.26:8081/
webpack output is served from /
Content not from webpack is served from /Users/MacBookPro/Desktop/test/www
Hash: e47c2c5adc06bd491cdb
Version: webpack 3.8.1
Time: 3348ms
                                        Asset       Size  Chunks                    Chunk Names
i-f7-ios.png?b356cb6518f2679e2645d1224914af9a    7.29 kB          [emitted]
                 e47c2c5adc06bd491cdb.main.js    2.05 MB       0  [emitted]  [big]  main
                                   index.html  404 bytes          [emitted]
[./node_modules/framework7/dist/js/framework7.js] ./node_modules/framework7/dist/js/framework7.js 830 kB {0} [built]
[./node_modules/loglevel/lib/loglevel.js] ./node_modules/loglevel/lib/loglevel.js 7.86 kB {0} [built]
[./node_modules/strip-ansi/index.js] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
[./node_modules/url/url.js] ./node_modules/url/url.js 23.3 kB {0} [built]
[./node_modules/vue/dist/vue.common.js] ./node_modules/vue/dist/vue.common.js 287 kB {0} [built]
   [0] multi (webpack)-dev-server/client?http://192.168.2.26:8081 webpack/hot/dev-server ./src/main.js ./webpack/dev_helpers/CordovaDeviceRouter.js 64 bytes {0} [built]
[./node_modules/webpack-dev-server/client/index.js?http://192.168.2.26:8081] (webpack)-dev-server/client?http://192.168.2.26:8081 7.95 kB {0} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.56 kB {0} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {0} [built]
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1 kB {0} [built]
[./src/assets/sass/main.scss] ./src/assets/sass/main.scss 1.1 kB {0} [built]
[./src/main.js] ./src/main.js 1.07 kB {0} [built]
[./src/main.vue] ./src/main.vue 1.41 kB {0} [built]
[./src/routes.js] ./src/routes.js 313 bytes {0} [built]
[./webpack/dev_helpers/CordovaDeviceRouter.js] ./webpack/dev_helpers/CordovaDeviceRouter.js 595 bytes {0} [built]
    + 47 hidden modules

ERROR in ./webpack/dev_helpers/CordovaDeviceRouter.js
Module not found: Error: Can't resolve 'device.js' in '/Users/MacBookPro/Desktop/test/webpack/dev_helpers'
 @ ./webpack/dev_helpers/CordovaDeviceRouter.js 1:17-37
 @ multi (webpack)-dev-server/client?http://192.168.2.26:8081 webpack/hot/dev-server ./src/main.js ./webpack/dev_helpers/CordovaDeviceRouter.js
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks  Chunk Names
    index.html  588 kB       0
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 887 bytes {0} [built]
    [./node_modules/lodash/lodash.js] ./node_modules/lodash/lodash.js 540 kB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 488 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 495 bytes {0} [built]
webpack: Failed to compile.
^C
```

I just installed the projects:
```
cordova create test vue.test.app Test --template cordova-template-framework7-vue-webpack
```

Nothing else. Then ran ```cordova run ios -- --lr``` and ```cordova run browser -- --lr```. Both causing the same error.

**Comment by josteph** [comment]
Have you run: `npm i` ?

If you have done it, you need to change your `package.json` dependencies to follow this [commit](https://github.com/centrual/cordova-template-framework7-vue-webpack/commit/7960e8fb0ebd802a8b6d98615f1c4a8e8982261c)

For more information step by step:

1.  Run `npm install --save-dev current-device`
2.  Go to `/webpack/dev_helpers` directory, find `CordovaDeviceRouter.js`
3.  Change the first line to `const deviceJs = require('current-device').default`
4.  If you want to confirm that `cordova.js` script has been injected depending on platform, you can change:

> console.log(`${platform} platform cordova.js injected.`)

to 

> alert(`${platform} platform cordova.js injected`)

I hope this helps for other people as well.

Please close the issue after your problem has been solved!

**Comment by renege** [comment]
Great! Except that it's not actually live realoading. When I change an asset, it isn't compiled and shown in browser as a result.

**Comment by josteph** [comment]
In my case, if you change a vue component while running on `--lr` command, that's correct. It will display it as white page as a result of hot update.

All you need to do is to refresh the application (refresh page if on browser).

Webpack is powerful, if it is not compiled it will definitely give you error output.

Below is screenshot if webpack detects changes on your files (and if you press save button though).
![image](https://user-images.githubusercontent.com/13672022/33380910-8274bf56-d557-11e7-8f42-6c315e63d104.png)

EDIT:
scss file gets compiled without you need to refresh the page!

**Comment by renege** [comment]
I even get this error @josteph :

```
cordova run ios -- --lr
Before deploy hook started...
Checking is node modules installed...
Node modules already installed.
Watcher ready!
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8081
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3
```

**Comment by josteph** [comment]
Yes, you need to reopen the terminal and re-run the command again.

**Comment by caiobiodere** [comment]
I think that feedback is fine, i will close this issue
